version: "3"
services:
  database:
    image: "mongo:latest"
    container_name: napa-solution-database
    environment:
      - MONGO_INITDB_DATABASE=napa-solution-database
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Password1
    # ports:
    #   - "27017:27017"
    # volumes:
    #   - ./napa-website-data/data:/data/db

  # automate restore data
  # comment this code if you dont want restore data automacy
  # automatic data restore can be cause data duplicate, redundant.
  mongo-seed:
    image: "mongo:latest"
    links:
      - database
    volumes:
      - ./napa-website-data:/data
    command: mongorestore --uri mongodb://root:Password1@database:27017 -d admin /data/admin

  # all in docker
  app:
    # image: node:latest
    container_name: "napa-solution-server"
    # command: sh -c "ping google.com"
    # working_dir: /app
    # volumes:
    #   - ./node_modules:/napa-web-api/node_modules
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
